---
- name: Install dependencies and build application
  hosts: localhost  # ou spécifiez vos hosts cibles
  become: false       # si besoin de privilèges élevés
  vars:
    project_dir: "/var/jenkins_home/workspace/build-app-angular" 
  
  tasks:
    - name: Install Node.js dependencies
      command: npm install
      args:
        chdir: {{ project_dir }} # chemin vers votre répertoire de projet

    - name: Build applications
      command: npm run build
      args:
        chdir: {{ project_dir }}  # chemin vers votre répertoire de projet