- name: Installer les dépendances et builder l'application
  hosts: localhost
  become: false
  vars_files:
    - "ansible/vars/environments/localhost.yml"  # Chemin fixe pour les variables

  tasks:
    - name: Install Node.js dependencies
      command: "{{ install_command | default('npm Install') }}"
      args:
        chdir: "{{ project_dir }}" # chemin vers votre répertoire de projet

    - name: Build applications
      command: "{{ build_command }}"
      args:
        chdir: "{{ project_dir }}"  # chemin vers votre répertoire de projet