- name: Installer les dépendances et builder l'application
  hosts: localhost
  become: false
  vars_files:
      - "{{ playbook_dir }}/../vars/environments/localhost.yml"

  tasks:
    - name: Install Node.js dependencies
      command: "{{ install_command | default('npm Install') }}"
      args:
        chdir: "{{ project_dir }}" # chemin vers votre répertoire de projet
        
    - name: Angular ESLint Validatio
      command: npm run lint
      args:
        chdir: "{{ project_dir }}"

    - name: Build applications
      command: "{{ build_command }}"
      args:
        chdir: "{{ project_dir }}"  # chemin vers votre répertoire de projet

    - name: Run angular Test 
      command: npm run test
      args: 
        chdir: "{{ project_dir }}"