- name: Installer les dépendances et builder l'application
  become: false
  vars_files:
    - "{{ playbook_dir }}/../vars/environments/localhost.yml"

  tasks:
    - name: Install Node.js dependencies
      command: "{{ install_command }}"
      args:
        chdir: "{{ project_dir }}" # chemin vers votre répertoire de projet

    - name: Build applications
      command: "{{ build_command }}"
      args:
        chdir: "{{ project_dir }}"  # chemin vers votre répertoire de projet