---
- name: Install dependencies and build application
  hosts: localhost  # ou spécifiez vos hosts cibles
  become: false       # si besoin de privilèges élevés
  vars_files: 
    - "vars/environments/{{ ansible_host }}.yml"

  tasks:
    - name: Install Node.js dependencies
      command: "{{ install_command | default('npm Install') }}"
      args:
        chdir: "{{ project_dir }}" # chemin vers votre répertoire de projet

    - name: Build applications
      command: "{{ build_command }}"
      args:
        chdir: "{{ project_dir }}"  # chemin vers votre répertoire de projet